name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]  # Replace `main` with your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Replace with your requirements file

      - name: Prepare Hugging Face Spaces credentials
        run: |
          echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> $GITHUB_ENV
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV

      - name: Deploy to Hugging Face Spaces
        uses: huggingface/spaces-action@v1
        with:
          repo: 'rahulathreya45/Workout_form_checker'  # Replace with your repo
          branch: ${{ github.sha }}
          commit: ${{ github.sha }}
          secret: ${{ secrets.HF_TOKEN }}

